pipeline {
  agent any
  parameters {
    choice(
      choices: ['create' , 'delete'],
      description: 'What is the action you like to perform?',
      name: 'REQUESTED_ACTION'
    )
  }
  stages {
    stage('Create k8s cluster') {
      when {
        expression { params.REQUESTED_ACTION == 'create' }
      }
      steps {
        withAWS(credentials: 'aws_credentials', region: 'eu-central-1') {
          sh 'eksctl create cluster -f cluster/cluster.yaml'
        }
      }
    }
    stage('Update kubeconfig') {
      when {
        expression { params.REQUESTED_ACTION == 'create' }
      }
      steps {
        withAWS(credentials: 'aws_credentials', region: 'eu-central-1') {
          sh 'aws eks --region eu-central-1 update-kubeconfig --name capstone-cluster'
        }
      }
    }
    stage('Delete k8s cluster') {
      when {
        expression { params.REQUESTED_ACTION == 'delete' }
      }
      steps {
        withAWS(credentials: 'aws_credentials', region: 'eu-central-1') {
          sh 'eksctl delete cluster -f cluster/cluster.yaml'
        }
      }
    }
  }
}