pipeline {
  agent any
  stages {
    stage('Create k8s cluster') {
      steps {
        withAWS(credentials: 'aws_credentials', region: 'eu-central-1') {
          sh 'eksctl create cluster -f cluster/cluster.yaml'
        }
      }
    }
  }
}