pipeline {
  agent any
  stages {
    stage('Lint HTML') {
      steps {
        sh 'tidy -q -e **/*.html'
      }
    }

    stage('Build Docker Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USER')]) {
          sh 'docker build -t schnebelalexander/capstone deployment/'
        }
      }
    }

    stage('Push Docker Image to Dockerhub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USER')]) {
					sh '''
						docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
						docker push schnebelalexander/capstone
					'''
				}
      }
    }
  }
}